# [优化性能]
# 使用 GPU 渲染
vo=gpu-next
gpu-api=auto

# 开启硬件解码
hwdec=auto-safe

# 启用刷新率同步
video-sync=display-resample
interpolation=yes
tscale=oversample

# 优化 OSD 渲染
osd-on-seek=no
osd-bar=no

# [杂项]
# 记住播放进度（下次打开自动接着看）
save-position-on-quit=yes

# 默认语言优先选择中文（如果是多语言视频）
alang=zh,chi,chs,en
slang=zh,chi,chs,en
