[FileDialog]
history=file:///home/dengzengxiao/data/SFLS/\x4e5d\x4e0a/\x8bed\x6587, file:///home/dengzengxiao/Downloads, file:///home/dengzengxiao
lastVisited=file:///home/dengzengxiao/data/SFLS/\x4e5d\x4e0a/\x8bed\x6587
qtVersion=5.15.18
shortcuts=file:, file:///home/dengzengxiao
sidebarWidth=78
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xb0\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0}\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xbb\0\0\0\x1\0\0\0\0\0\0\0\x41\0\0\0\x1\0\0\0\0\0\0\0\x41\0\0\0\x1\0\0\0\0\0\0\0s\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=List
