[FileDialog]
history=file:///home/dengzengxiao/data/SFLS/八下/English/外教/Chapter 8, file:///home/dengzengxiao/data/SFLS/八下/语文/期末考试, file:///home/dengzengxiao/data/SFLS/八下/语文, file:///home/dengzengxiao/data/SFLS/八下/物理/暑假作业, file:///home/dengzengxiao
lastVisited=file:///home/dengzengxiao
qtVersion=6.11.1
shortcuts=file:, file:///home/dengzengxiao
sidebarWidth=78
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xb0\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xbb\0\0\0\x1\0\0\0\0\0\0\0\x41\0\0\0\x1\0\0\0\0\0\0\0\x41\0\0\0\x1\0\0\0\0\0\0\0s\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=List
